### ISSUE TITLE
Now is easier to maintain compatibility with newer Nextcloud releases

### ISSUE THREAD

**Issue by p-bo** [newhinton/quickaccesssorting#12]
Just in case it wasn't noticed - Nextcloud improved policy regarding changes in core to ease app developers in maintaining compatibility with newer Nextcloud versions:  https://help.nextcloud.com/t/new-process-for-documenting-core-code-changes-that-affect-app-developers/149828?u=p-bo

**Comment by livier** [comment]
Not available for nextcloud 25 ?

**Comment by newhinton** [comment]
@livier Oops, it seems that i forgot to actually make a release.

The app should be fully compatible, even if it is "untested".
I will create a release very soon!

**Comment by newhinton** [comment]
I fixed it, sorry for the delays.

**Comment by p-bo** [comment]
Thanks :-)
