### ISSUE TITLE
Nextcloud 18 compatibility

### ISSUE THREAD

**Issue by lapineige** [newhinton/quickaccesssorting#2]
This app is not compatible with Nextcloud 18.
Is that a complete incompatibility issue (change of dependency/Nextcloud code that break the app), or is it possible to upgrade the code to make it working ?
If it's the second case, do you plan to upgrade it ? I can help testing it if needed :)

Note: I'm asking to know if an upgrade is scheduled, not to rush you :)

**Comment by newhinton** [comment]
I found out quiet recently that it "broke", but that is only due to the app not having the proper max server version. I'll change that in the next few days

**Comment by newhinton** [comment]
This should be fixed now:
https://github.com/newhinton/quickaccesssorting/releases/tag/1.0.3

**Comment by lapineige** [comment]
Great !

**Comment by lapineige** [comment]
But I don't understand how it is supposed to work: in favorite view or the normal file view, I understood that it's hidden in the parameters, yet changing sorting value does nothing.
Could you please explain it to me ?

**Comment by newhinton** [comment]
First you need to mark some folders as favorite. They have a yellow star above them. 

When you did that, the navigationbar on the left side lets you expand the 'Favorites'-entry. 

it should show your favourite folders in your choosen order.

you can change the order in the dropdown which is hidden in the settings in the left
