### ISSUE TITLE
App doesn't appear to do anything on NC v20

### ISSUE THREAD

**Issue by aproposnix** [newhinton/quickaccesssorting#4]
I only just realized that this app existed because an update was pushed to my server. I went ahead and upgraded but I see no change in behavior.  I've looked at the screens shown on github and I see nothing like that. Is there some setting that needs to be turned on or something? What am I missing? 

Edit: There are no errors or warnings in the logs.

**Comment by newhinton** [comment]
i assume you are using v.1.1.1 on nc 20?

if the app is enabled, you can mark folders as favorite, and then expand the favorites-menu-entry in the files app. There you can drag the entries around, reordering them. Is that not possible?

**Comment by aproposnix** [comment]
@newhinton Sorry, yeah it's version 1.1.1 on NC 20. I have the app enabled, but I do not see the functionality to describe.

**Comment by newhinton** [comment]
is the menu showing up in the settings?
do you have javascript-errors?

**Comment by aproposnix** [comment]
See the images in the previous post. The menu hasn't changed. In the browser developer tools I don't see JS errors.

**Comment by newhinton** [comment]
@aproposnix 

you are right, i can recreate your findings. i have an idea why that is, i will push an update as soon as i find the bug :D

**Comment by aproposnix** [comment]
Sorry, I'm a little dense today... there was a JS error 
http://pix.toile-libre.org/upload/original/1603140506.png

**Comment by newhinton** [comment]
okay, i have to say this is confusing. it should work, but sometimes it does not. could you completely remove the app (apps->quickaccessorting->disable & remove) and then reinstall it?

**Comment by aproposnix** [comment]
I tried it but it did not fix anything :(

**Comment by newhinton** [comment]
yeah, i had that too. I think it has something to do with the changes nc introduced to the appstructure, but i could not validate that. But its good that it works now!

**Comment by aproposnix** [comment]
Seems I closed this prematurely as the app just stopped working. Maybe once my cache was removed from the browser? Should i open a new ticket?

**Comment by newhinton** [comment]
@aproposnix when the app stopped working, did the error show up again?
do you have access to the server? if yes, could you delete the following file: 
nc_root_dir/apps/quickaccesssorting/appinfo/app.php

**Comment by aproposnix** [comment]
I don't have access at the moment. I'll try it later this evening though.

**Comment by nsrafk** [comment]
I have the same issue. Running NC 20.0.1 

No functionality

**Comment by nsrafk** [comment]
Take a look at https://github.com/nextcloud/server/issues/23893

It seems your app is creating bugs 😊

I solved my problems by disabling your app.

**Comment by newhinton** [comment]
@nsrafk 
thanks for the report! that is a very strange sideeffect, i'll have to investigate that. The original error, that the app doesnt do anything seems to be nonexistent, or at least not reproducible. all in all, while this app works flawless with 19, 20 seems to be very unstable. maybe i'll have the time for it next weekend, but i'll keep you updates

**Comment by newhinton** [comment]
@aproposnix I found out how i can reproduce this error. It is a chrome-specific error that does not show up on firefox. That explains why i cannot reproduce it (and it also explains #5)
