### ISSUE TITLE
Nextcloud 22 compatibility

### ISSUE THREAD

**Issue by LakkesW** [newhinton/quickaccesssorting#6]
Please add support for NC 22. Thanks!

**Comment by Mc0023** [comment]
It seems to be working without issue on NC 22 so I think it can be added to include 22 support.

**Comment by newhinton** [comment]
Oh yeah i probably should do this! 

I will check 23 aswell and update the app in the first week of 2022!

**Comment by livier** [comment]
Tryed a pull request ... my first one !
Was it correct ? or unusefull ?

**Comment by newhinton** [comment]
@livier Thank you for your help!

Two small things:

1. You did not actually open a Pull request, you can do so in the [Pull Requests Tab](https://github.com/newhinton/quickaccesssorting/pulls) or [here](https://github.com/newhinton/quickaccesssorting/compare/master...livier:master) ;)
2. That is something you could not know: When creating a new version for an app, nextcloud would like a new version. The version is also defined in the [info.xml](https://github.com/livier/quickaccesssorting/blob/d6c7c4b68028fdfa4bb02f637e1a13b048500819/appinfo/info.xml#L7). We use [Semantic Versioning](https://semver.org/), if you are not familiar with it, this change would be a patch, and the version would therefore be 1.1.3.

On a sidenote, did you test this app with Nextcloud 23 already? If you did, we could "skip" 22, and you could increase the max-version to 23 directly. 

Again, thank you!

**Comment by newhinton** [comment]
@livier I also tested Nextcloud 23. If you want, you can bump the max version again in your PR!

**Comment by SuperSandro2000** [comment]
> @livier will you create a pr? Otherwise i will update the version accordingly

I think it is save to assume that it will be way faster if you do it yourself.

**Comment by newhinton** [comment]
@SuperSandro2000 True, but i wanted to give him or her a chance. It's always nice to be included! :)

**Comment by newhinton** [comment]
Closed by #7
